[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "basedetect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.11.0.86",
    "numpy>=1.26.0",
    "ultralytics>=8.3.217",
    "torch==2.8",
    "torchvision>=0.23.0",
    "opencv-contrib-python>=4.13.0.92",
    "apriltag-python>=3.4.5",
]

[tool.setuptools.packages.find]
include = ["basedetect*", "sdk*"]
