predict:
  type: "status"

  common:
    output: "artifacts/outputs/output.avi"
    device: "auto"
    conf: 0.25
    save: true
    show: true

  status:
    source: "test/test7-2.mp4"
    weights: "models/data-3tag-v2.pt"

  base_coord:
    source: "test/test7-2.mp4"
    weights: "models/data-v8-base.pt"
    camera_config: "configs/camera.yaml"
    coord3d: true
    apriltag: false
    apriltag_family: null
    apriltag_size: null
